/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/gH7giaYtDLt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { JSX, SVGProps } from "react"


export function DashboardFromV() {
  return (
    <div className="relative h-screen w-full">
      <div className="absolute inset-0 bg-[url('/placeholder.svg?height=1080&width=1920')] bg-cover bg-center" />
      <div className="relative z-10 flex h-full flex-col">
        <div className="flex-1 overflow-auto">
          <div className="mx-auto max-w-md p-4">
            <div className="flex items-center space-x-2">
              <SparklesIcon className="h-6 w-6 text-blue-500" />
              <Input className="flex-1" placeholder="What should I wear today?" />
            </div>
            <h1 className="mt-6 mb-4 text-4xl font-bold text-center text-gray-900 dark:text-gray-100">
              Build Your Dream Wardrobe with AI
            </h1>
            <div className="relative">
              <Card className="p-4 shadow-lg">
                <div className="flex justify-between mb-4">
                  <h2 className="text-2xl font-semibold text-gray-900 dark:text-gray-100">Your Wardrobe</h2>
                  <Button className="text-blue-500" variant="ghost">
                    AI Inspirations
                  </Button>
                </div>
                <div className="flex space-x-4 overflow-x-auto">
                  <Card className="p-4 shrink-0">
                    <img
                      alt="Footwear"
                      className="rounded-md"
                      height="100"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "100/100",
                        objectFit: "cover",
                      }}
                      width="100"
                    />
                    <p className="mt-2 text-center text-gray-700 dark:text-gray-300">Footwear</p>
                  </Card>
                  <Card className="p-4 shrink-0">
                    <img
                      alt="Shirts"
                      className="rounded-md"
                      height="100"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "100/100",
                        objectFit: "cover",
                      }}
                      width="100"
                    />
                    <p className="mt-2 text-center text-gray-700 dark:text-gray-300">Shirts</p>
                  </Card>
                  <Card className="p-4 shrink-0">
                    <img
                      alt="Jackets"
                      className="rounded-md"
                      height="100"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "100/100",
                        objectFit: "cover",
                      }}
                      width="100"
                    />
                    <p className="mt-2 text-center text-gray-700 dark:text-gray-300">Jackets</p>
                  </Card>
                  <Card className="p-4 shrink-0">
                    <img
                      alt="Accessories"
                      className="rounded-md"
                      height="100"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "100/100",
                        objectFit: "cover",
                      }}
                      width="100"
                    />
                    <p className="mt-2 text-center text-gray-700 dark:text-gray-300">Accessories</p>
                  </Card>
                </div>
              </Card>
            </div>
            <div className="relative mt-6 space-y-4">
              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-gray-900 dark:text-gray-100">Lookbook</h2>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <Card className="p-4 shadow-lg">
                    <img
                      alt="Hottest arrivals this season"
                      className="rounded-md"
                      height="200"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "400/200",
                        objectFit: "cover",
                      }}
                      width="400"
                    />
                    <p className="mt-2 text-center text-gray-700 dark:text-gray-300">Hottest arrivals this season</p>
                  </Card>
                  <Card className="p-4 shadow-lg">
                    <img
                      alt="New season trends"
                      className="rounded-md"
                      height="200"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "400/200",
                        objectFit: "cover",
                      }}
                      width="400"
                    />
                    <p className="mt-2 text-center text-gray-700 dark:text-gray-300">New season trends</p>
                  </Card>
                  <Card className="p-4 shadow-lg">
                    <img
                      alt="Exclusive collections"
                      className="rounded-md"
                      height="200"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "400/200",
                        objectFit: "cover",
                      }}
                      width="400"
                    />
                    <p className="mt-2 text-center text-gray-700 dark:text-gray-300">Exclusive collections</p>
                  </Card>
                </div>
              </section>
            </div>
          </div>
        </div>
        {/* <nav className="border-t bg-white dark:bg-gray-900 p-4">
          <div className="flex justify-around">
            <HomeIcon className="h-6 w-6 text-gray-700 dark:text-gray-300" />
            <SquareIcon className="h-6 w-6 text-purple-600 dark:text-purple-400" />
            <HeartIcon className="h-6 w-6 text-gray-700 dark:text-gray-300" />
          </div>
        </nav> */}
      </div>
    </div>
  )
}

function HeartIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>
  )
}


function HomeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function SparklesIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z" />
      <path d="M5 3v4" />
      <path d="M19 17v4" />
      <path d="M3 5h4" />
      <path d="M17 19h4" />
    </svg>
  )
}


function SquareIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
    </svg>
  )
}
